@echo off
setlocal
set "FLEET_ORIGINAL_EDITOR_JSON=__FLEET_ORIGINAL_EDITOR_JSON__"
set "FLEET_INTEGRATION_VERSION=__FLEET_INTEGRATION_VERSION__"
"__FLEET_NODE__" "__FLEET_CONSOLE__" %*
exit /b %ERRORLEVEL%
